/**
 * OCP Microscaling Formats (MX) Specifications
 * Contains definitions for FP8, FP6, and FP4 formats
 */

export const FORMATS = {
  fp16: {
    name: "half (fp16)",
    totalBits: 16,
    exponentBits: 5,
    mantissaBits: 10,
    exponentBias: 15,
    hasInfinity: true,
    hasNaN: true,
  },
  bf16: {
    name: "bfloat16 (bf16)",
    totalBits: 16,
    exponentBits: 8,
    mantissaBits: 7,
    exponentBias: 127,
    hasInfinity: true,
    hasNaN: true,
  },
  e4m3: {
    name: "fp8 (e4m3)",
    totalBits: 8,
    exponentBits: 4,
    mantissaBits: 3,
    exponentBias: 7,
    hasInfinity: false,
    hasNaN: true,
    nanPatterns: [0b011111_11], // all mantissa bits must also be 1
  },
  e5m2: {
    name: "fp8 (e5m2)",
    totalBits: 8,
    exponentBits: 5,
    mantissaBits: 2,
    exponentBias: 15,
    hasInfinity: true,
    hasNaN: true,
    hasZeroes: true,
  },
  e8m0: {
    name: "e8 (e8m0)",
    totalBits: 8,
    exponentBits: 8,
    mantissaBits: 0,
    exponentBias: 127,
    hasInfinity: false,
    hasNaN: true,
    hasZeroes: false,
  },
  e2m3: {
    name: "fp6 (e2m3)",
    totalBits: 6,
    exponentBits: 2,
    mantissaBits: 3,
    exponentBias: 1,
    hasInfinity: false,
    hasNaN: false,
    hasZeroes: true,
  },
  e3m2: {
    name: "fp6 (e3m2)",
    totalBits: 6,
    exponentBits: 3,
    mantissaBits: 2,
    exponentBias: 3,
    hasInfinity: false,
    hasNaN: false,
    hasZeroes: true,
  },
  e2m1: {
    name: "fp4 (e2m1)",
    totalBits: 4,
    exponentBits: 2,
    mantissaBits: 1,
    exponentBias: 1,
    hasInfinity: false,
    hasNaN: false,
    hasZeroes: true,
  },
};
